# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/lorenzo/Epic/UnrealEngine

TARGETS = \
	NetworkTest-Android-DebugGame  \
	NetworkTest-Android-Development  \
	NetworkTest-Android-Shipping  \
	NetworkTest-Linux-DebugGame  \
	NetworkTest-Linux-Development  \
	NetworkTest-Linux-Shipping  \
	NetworkTest-LinuxArm64-DebugGame  \
	NetworkTest-LinuxArm64-Development  \
	NetworkTest-LinuxArm64-Shipping  \
	NetworkTest \
	NetworkTestEditor-Linux-DebugGame  \
	NetworkTestEditor-Linux-Development  \
	NetworkTestEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend NetworkTestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug NetworkTestEditor-Linux-Debug


NetworkTest-Android-DebugGame:
	 $(BUILD) NetworkTest Android DebugGame  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-Android-Development:
	 $(BUILD) NetworkTest Android Development  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-Android-Shipping:
	 $(BUILD) NetworkTest Android Shipping  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-Linux-DebugGame:
	 $(BUILD) NetworkTest Linux DebugGame  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-Linux-Development:
	 $(BUILD) NetworkTest Linux Development  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-Linux-Shipping:
	 $(BUILD) NetworkTest Linux Shipping  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-LinuxArm64-DebugGame:
	 $(BUILD) NetworkTest LinuxArm64 DebugGame  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-LinuxArm64-Development:
	 $(BUILD) NetworkTest LinuxArm64 Development  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest-LinuxArm64-Shipping:
	 $(BUILD) NetworkTest LinuxArm64 Shipping  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTest: NetworkTest-Linux-Development

NetworkTestEditor-Linux-DebugGame:
	 $(BUILD) NetworkTestEditor Linux DebugGame  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTestEditor-Linux-Development:
	 $(BUILD) NetworkTestEditor Linux Development  -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" $(ARGS)

NetworkTestEditor: NetworkTestEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/lorenzo/Documents/Unreal Projects/NetworkTest/NetworkTest.uproject" -Game 

.PHONY: $(TARGETS)
